---
--- Generated by Luanalysis
--- Created by landers.
--- DateTime: 2022/9/2 19:28
---

--自动重载app map映射
--每1min重载一次 记录修改时间

local ngx = require('ngx');
local app_loader = require('load_apps');

function reload()
    local delay = 120;
    --仅在主进程执行
    if (0==ngx.worker.id()) then
        local ok, err = ngx.timer.every(delay, reload_map);
        if not ok then
            ngx.log(ngx.ERR, 'failed to reload from apps map: ', err);
            return;
        end
    end
end

function reload_map()
    local apps_tmp = app_loader.loadApps();
    if (apps_tmp ~= nil) then
        apps = apps_tmp;
        ngx.log(ngx.STDERR, 'reload from apps map');
        for key, value in pairs(apps) do
            ngx.log(ngx.STDERR, 'app:', key, ' stat:', value['stat'], ' domain:', value['domain']);
        end
    end
end

reload();