---
--- Generated by Luanalysis
--- Created by landers.
--- DateTime: 2022/8/31 20:47
---

--在不合法时自定义的响应

local ngx = require('ngx');

--错误
local function resErr()
    ngx.header['Content-Type'] = 'text/html;charset:utf-8';
    ngx.exit(ngx.HTTP_FORBIDDEN);
end

--服务已经停止
local function resStop()
    ngx.header['Content-Type'] = 'text/html;charset:utf-8';
    ngx.say(page_stop);
    ngx.exit(ngx.HTTP_BAD_REQUEST);
end

return {resErr = resErr, resStop = resStop}