---
--- Generated by Luanalysis
--- Created by landers.
--- DateTime: 2022/8/31 20:47
---

--控制响应头 包括NoEngine的信息
local ngx = require('ngx');

function addHeaders()
    ngx.header.Server = 'NoEngine';
    ngx.header.Copyright = 'renj.io';
    ngx.header.Author = 'github.com/landers1037';
end

addHeaders();